---
AWSTemplateFormatVersion: 2010-09-09
Description: TagIT AWS Infrastructure
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: 'Please provide the following parameter values:'
      Parameters:
      - pDBPassword
      - pNotifyEmail
      - pEC2KeyPairBastion
      - pEC2KeyPair
      - pAvailabilityZoneA
      - pAvailabilityZoneB
    - Label:
        default: AWS Quick Start Configuration
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
    ParameterLabels:
      pDBPassword:
        default: Database Password
      pNotifyEmail:
        default: Notification Email Address
      pEC2KeyPairBastion:
        default: Existing SSH Key for the Bastion Instance
      pEC2KeyPair:
        default: Existing SSH Key for Other Instances
      pAvailabilityZoneA:
        default: First Availability Zone
      pAvailabilityZoneB:
        default: Second Availability zone
      pVPCTenancy:
        default: Instance tenancy
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
  Stack:
    Value: 0
  VersionDate:
    Value: 20160518
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in nested stacks
  Output:
    Description: N/A
Parameters:
  pDBPassword:
    Description: Mixed alphanumeric and must be between 8 and 28 characters and contain
      at least one capital letter
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 28
    AllowedPattern: '[a-zA-Z0-9!^*\-_+]*'
    ConstraintDescription: Can only contain alphanumeric characters or the following
      special characters !^*-_+, between 8 and 28 characters
  pNotifyEmail:
    Description: Notification email address for security events (you will receive
      a confirmation email)
    Type: String
    Default: distlist@example.org
  pEC2KeyPairBastion:
    Description: The SSH key pair in your account to use for the bastion host login
    Type: AWS::EC2::KeyPair::KeyName
  pEC2KeyPair:
    Description: The SSH key pair in your account to use for all other EC2 instance
      logins
    Type: AWS::EC2::KeyPair::KeyName
  pAvailabilityZoneA:
    Description: Availability Zone 1
    Type: AWS::EC2::AvailabilityZone::Name
  pAvailabilityZoneB:
    Description: Availability Zone 2
    Type: AWS::EC2::AvailabilityZone::Name
  pVPCTenancy:
    Description: Instance tenancy behavior for this VPC
    Type: String
    Default: default
    AllowedValues:
    - default
    - dedicated
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, periods (.), and hyphens (-). It cannot start or
      end with a hyphen (-).
    Default: quickstart-reference
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-]+(/[0-9a-zA-Z-]+)*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/). It cannot start or end
      with forward slash (/) because they are automatically appended.
    Default: enterprise-accelerator/pci/latest
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/). It cannot start or end with forward slash (/) because they
      are automatically appended.
    Type: String

Mappings:
  CustomVariables:
    vResourceEnvironmentTagKey:
      Value: Environment
    vResourceEnvironmentTagValue:
      Value: development
  RegionServiceSupport:
    us-east-1:
      NatGateway: true
      Glacier: true
    us-east-2:
      NatGateway: true
      Glacier: true
    us-west-1:
      NatGateway: true
      Glacier: true
    us-west-2:
      NatGateway: true
      Glacier: true
    ca-central-1:
      NatGateway: true
      Glacier: true
    eu-central-1:
      NatGateway: true
      Glacier: true
    eu-west-1:
      NatGateway: true
      Glacier: true
    eu-west-2:
      NatGateway: true
      Glacier: true
    ap-northeast-1:
      NatGateway: true
      Glacier: true
    ap-northeast-2:
      NatGateway: true
      Glacier: true
    ap-south-1:
      NatGateway: true
      Glacier: true
    ap-southeast-1:
      NatGateway: true
      Glacier: false
    ap-southeast-2:
      NatGateway: true
      Glacier: true
    sa-east-1:
      NatGateway: true
      Glacier: false
    us-gov-west-1:
      NatGateway: false
      Glacier: false
  AWSAMIRegionMap:
    AMI:
      AMZNLINUXHVM: amzn-ami-hvm-2017.03.1.20170812-x86_64-gp2
    ap-northeast-1:
      AMZNLINUXHVM: ami-4af5022c
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    ap-northeast-2:
      AMZNLINUXHVM: ami-8663bae8
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    ap-south-1:
      AMZNLINUXHVM: ami-d7abd1b8
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    ap-southeast-1:
      AMZNLINUXHVM: ami-fdb8229e
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    ap-southeast-2:
      AMZNLINUXHVM: ami-30041c53
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    ca-central-1:
      AMZNLINUXHVM: ami-5ac17f3e
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    eu-central-1:
      AMZNLINUXHVM: ami-657bd20a
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    eu-west-1:
      AMZNLINUXHVM: ami-ebd02392
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    eu-west-2:
      AMZNLINUXHVM: ami-489f8e2c
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    sa-east-1:
      AMZNLINUXHVM: ami-d27203be
      InstanceType: t2.small
      InstanceTypeDatabase: db.m3.large
    us-east-1:
      AMZNLINUXHVM: ami-4fffc834
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    us-east-2:
      AMZNLINUXHVM: ami-ea87a78f
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    us-gov-west-1:
      AMZNLINUXHVM: ami-ffa61d9e
      InstanceType: t2.small
      InstanceTypeDatabase: db.m3.large
    us-west-1:
      AMZNLINUXHVM: ami-3a674d5a
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small
    us-west-2:
      AMZNLINUXHVM: ami-aa5ebdd2
      InstanceType: t2.small
      InstanceTypeDatabase: db.t2.small

Conditions:
  LaunchAsDedicatedInstance:
    !Equals
    - !Ref pVPCTenancy
    - dedicated

Resources:
  IamTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-tagit-templates/iam.yml
      TimeoutInMinutes: 20

  LoggingTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-tagit-templates/logging.yml
      TimeoutInMinutes: 20
      Parameters:
        pNotifyEmail: !Ref pNotifyEmail
        pSupportsGlacier:
          !FindInMap
          - RegionServiceSupport
          - !Ref AWS::Region
          - Glacier

  ProductionVpcTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-tagit-templates/vpc-production.yml
      TimeoutInMinutes: 20
      Parameters:
        pRegionAZ1Name: !Ref pAvailabilityZoneA
        pRegionAZ2Name: !Ref pAvailabilityZoneB
        pProductionVPCName: Production VPC
        pBastionSSHCIDR: 0.0.0.0/0
        pDMZSubnetACIDR: 10.100.10.0/24
        pDMZSubnetBCIDR: 10.100.20.0/24
        pManagementCIDR: 10.10.0.0/16
        pAppPrivateSubnetACIDR: 10.100.96.0/21
        pAppPrivateSubnetBCIDR: 10.100.119.0/21
        pDBPrivateSubnetACIDR: 10.100.194.0/21
        pDBPrivateSubnetBCIDR: 10.100.212.0/21
        pVPCTenancy: !Ref pVPCTenancy
        pEnvironment:
          !FindInMap
          - CustomVariables
          - vResourceEnvironmentTagValue
          - Value
        pSupportsNatGateway:
          !FindInMap
          - RegionServiceSupport
          - !Ref AWS::Region
          - NatGateway
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
  ManagementVpcTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn: ProductionVpcTemplate
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-tagit-templates/vpc-management.yml
      TimeoutInMinutes: 20
      Parameters:
        pProductionVPC:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rVPCProduction
        pRouteTableProdPrivate:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rRouteTableProdPrivate
        pRouteTableProdPublic:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rRouteTableProdPublic
        pProductionCIDR: 10.100.0.0/16
        pBastionSSHCIDR: 0.0.0.0/0
        pManagementCIDR: 10.10.0.0/16
        pManagementDMZSubnetACIDR: 10.10.1.0/24
        pManagementDMZSubnetBCIDR: 10.10.2.0/24
        pManagementPrivateSubnetACIDR: 10.10.20.0/24
        pManagementPrivateSubnetBCIDR: 10.10.30.0/24
        pManagementVPCName: Management VPC
        pEC2KeyPairBastion: !Ref pEC2KeyPairBastion
        pEC2KeyPair: !Ref pEC2KeyPair
        pVPCTenancy: !Ref pVPCTenancy
        pBastionAmi:
          !FindInMap
          - AWSAMIRegionMap
          - !Ref AWS::Region
          - AMZNLINUXHVM
        pRegionAZ1Name: !Ref pAvailabilityZoneA
        pRegionAZ2Name: !Ref pAvailabilityZoneB
        pEnvironment:
          !FindInMap
          - CustomVariables
          - vResourceEnvironmentTagValue
          - Value
        pBastionInstanceType:
          !If
          - LaunchAsDedicatedInstance
          - t2.small
          - t2.small
        pSupportsNatGateway:
          !FindInMap
          - RegionServiceSupport
          - !Ref AWS::Region
          - NatGateway
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix

  ApplicationTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn: ProductionVpcTemplate
    Properties:
      TemplateURL: https://s3.amazonaws.com/cfn-tagit-templates/application.yml
      TimeoutInMinutes: 30
      Parameters:
        pSecurityAlarmTopic:
          !GetAtt
          - LoggingTemplate
          - Outputs.rSecurityAlarmTopic
        pEC2KeyPair: !Ref pEC2KeyPair
        pProductionCIDR: 10.100.0.0/16
        pProductionVPC:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rVPCProduction
        pDMZSubnetA:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDMZSubnetA
        pDMZSubnetB:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDMZSubnetB
        pAppPrivateSubnetA:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rAppPrivateSubnetA
        pAppPrivateSubnetB:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rAppPrivateSubnetB
        pWebInstanceType:
          !FindInMap
          - AWSAMIRegionMap
          - !Ref AWS::Region
          - InstanceType
        pAppInstanceType:
          !FindInMap
          - AWSAMIRegionMap
          - !Ref AWS::Region
          - InstanceType
        pDBPrivateSubnetA:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDBPrivateSubnetA
        pDBPrivateSubnetB:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDBPrivateSubnetB
        pManagementCIDR: 10.10.0.0/16
        pRegionAZ1Name: !Ref pAvailabilityZoneA
        pRegionAZ2Name: !Ref pAvailabilityZoneB
        pWebServerAMI:
          !FindInMap
          - AWSAMIRegionMap
          - !Ref AWS::Region
          - AMZNLINUXHVM
        pAppAmi:
          !FindInMap
          - AWSAMIRegionMap
          - !Ref AWS::Region
          - AMZNLINUXHVM
        pDBUser: tagituserdb
        pDBName: tagitDB
        pDBPassword: !Ref pDBPassword
        pDBClass:
          !FindInMap
          - AWSAMIRegionMap
          - !Ref AWS::Region
          - InstanceTypeDatabase
        pEnvironment:
          !FindInMap
          - CustomVariables
          - vResourceEnvironmentTagValue
          - Value
        pBastionSSHCIDR: 0.0.0.0/0
        pSupportsGlacier:
          !FindInMap
          - RegionServiceSupport
          - !Ref AWS::Region
          - Glacier
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
Outputs:
  TemplateType:
    Value: Standard Multi-Tier Web Application
  TemplateVersion:
    Value: 1.0
  BastionIP:
    Description: Use this IP via SSH to connect to Bastion Instance
    Value:
      !GetAtt
      - ManagementVpcTemplate
      - Outputs.rBastionInstanceIP
  LandingPageURL:
    Value:
      !GetAtt
      - ApplicationTemplate
      - Outputs.LandingPageURL
  WebsiteURL:
    Value:
      !GetAtt
      - ApplicationTemplate
      - Outputs.WebsiteURL
